name: authentication
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  



  cupertino_icons: ^1.0.8
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true
