// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3YBEZBbDzBomUeOMuel09fFVnCABmxYQ',
    appId: '1:609478309225:web:bee357d8c3156f97e4b9f8',
    messagingSenderId: '609478309225',
    projectId: 'authentication-app-cbd7d',
    authDomain: 'authentication-app-cbd7d.firebaseapp.com',
    storageBucket: 'authentication-app-cbd7d.firebasestorage.app',
    measurementId: 'G-T15K2EM8D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGP9cK1JVsga9vHT9mLInRZBsPEwuBE5o',
    appId: '1:609478309225:android:a99ca90d7d71bd4ee4b9f8',
    messagingSenderId: '609478309225',
    projectId: 'authentication-app-cbd7d',
    storageBucket: 'authentication-app-cbd7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALVj98nhS_tzNGWqttHfv5qqmbP2TJZg',
    appId: '1:609478309225:ios:c61c6e835cc70ae4e4b9f8',
    messagingSenderId: '609478309225',
    projectId: 'authentication-app-cbd7d',
    storageBucket: 'authentication-app-cbd7d.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALVj98nhS_tzNGWqttHfv5qqmbP2TJZg',
    appId: '1:609478309225:ios:c61c6e835cc70ae4e4b9f8',
    messagingSenderId: '609478309225',
    projectId: 'authentication-app-cbd7d',
    storageBucket: 'authentication-app-cbd7d.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3YBEZBbDzBomUeOMuel09fFVnCABmxYQ',
    appId: '1:609478309225:web:8dabd7e98336d2eee4b9f8',
    messagingSenderId: '609478309225',
    projectId: 'authentication-app-cbd7d',
    authDomain: 'authentication-app-cbd7d.firebaseapp.com',
    storageBucket: 'authentication-app-cbd7d.firebasestorage.app',
    measurementId: 'G-5DCCGJFTK8',
  );
}
